### PR TITLE
Fixes user time created

### LINKED ISSUE #33: Fix user time being null
Some time user created time is null, so we need to make it more bullet proof

### PR DESCRIPTION
**Pull request by NejcZdovc**
Resolves #33

### CODE REVIEW

File: packages/sdk-core/src/common/utils.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ export const getMid = (eventName: string): string => {
     typeof performance.now === 'function'
   ) {
     const perf = performance.now()
+    console.log(perf)
```
Comment (pawan-blotout) [inline packages/sdk-core/src/common/utils.ts:13]: Need to remove

Comment (NejcZdovc) [reply packages/sdk-core/src/common/utils.ts]: removed

**Review by pawan-blotout — APPROVED** [review]
